name: scientific_programming
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7
  - jupyter
  - nodejs
  - jupyterlab
  - ipywidgets
  - numpy
  - matplotlib
  - pandas
  - statsmodels
  - seaborn
  - plotnine
  - pivottablejs
  - pandas-profiling
  - altair
  - vega_datasets
  - numba
  - cython
  - pip:
    - expyriment
    - pygame
    - jupyterlab-solutions
